spring:
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:mem:playvoice # test ??? ??? ??? ??? ???? ???.
        username: admin # username? password? ??? ??? ??
        password: admin1234
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create # ??????? ??? ? ??????? ????? ?? ??? ??
        properties:
            hibernate:
                format_sql: true # ???? query? ???

    redis:
        host: localhost
        port: 6379
        password: hjm4973

jwt:
    secret: wilflafe8w7fawf9fglrpobegmkv53EIF98fofvoenwkeof23wb9nvlk930jibnldeyu784xg
    access-validity-time: 3600000 # 60000 # 1분 600000 # 10분 3600000 # 1시간
    refresh-validity-time: 7776000000 # 300000 # 5분 1800000 # 30분 7776000000 # 3개월

logging.level:
    org.hibernate.SQL: debug