spring:
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:mem:playvoice # test ??? ??? ??? ??? ???? ???.
        username: admin # username? password? ??? ??? ??
        password: admin1234
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create # ??????? ??? ? ??????? ????? ?? ??? ??
        properties:
            hibernate:
                format_sql: true # ???? query? ???

logging.level:
    org.hibernate.SQL: debug